### ISSUE TITLE
Code does not compile with newest version of Raspberry Pi OS lite

### ISSUE THREAD

**Issue by craiglindley** [helioz2000/lvgl_demo#1]
I just loaded SD card minutes ago with latest release and downloaded the ready to go version of this program. Typed make and also sudo make and got the same message.

Here is the error message

pi@raspberrypi:~/littlevgl/lvgl_demo-master $ make
LDFLAGS ="-L/usr/local/lib"
Assembler messages:
Fatal error: can't create obj/lv_group.o: No such file or directory
make: *** [Makefile:54: obj/lv_group.o] Error 1

**Comment by craiglindley** [comment]
I found two issues:
1. the Make file didn't create an obj directory in the demo directory
2. Linking failed because it was looking for a mosquitto library which was not installed

I changed the Makefile to to remove mosquitto dependency and the code compiled and ran

**Comment by helioz2000** [comment]
Thanks for alerting me to this issue. Sorry, the Makefile was re-purposed from another project and I had forgotten to clean it up. Fixed now.
